CREATE TABLE `gift` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(128) NOT NULL,
    `avatar_url` VARCHAR(254) NOT NULL,
    `gif_url` VARCHAR (254) DEFAULT NULL,
    `price` INT(4) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `gift_giving` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `sender_id` BIGINT NOT NULL,
    `receiver_id` BIGINT NOT NULL,
    `gift_id` BIGINT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    CONSTRAINT `fk_giftgiving_senderid` FOREIGN KEY (sender_id) REFERENCES member(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_giftgiving_receiverid` FOREIGN KEY (receiver_id) REFERENCES member(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_giftgiving_giftid` FOREIGN KEY (gift_id) REFERENCES member(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `coin_spent` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `quantity` INT(4) NOT NULL,
    `usage_at` VARCHAR(8) NOT NULL,
    `reference` VARCHAR(254) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `member` ADD COLUMN `coins` INT(8) NOT NULL DEFAULT 0 AFTER `password`;
