CREATE TABLE `web_admin` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(254) NOT NULL,
    `password` VARCHAR(254) NOT NULL,
    `role` INT(1) NOT NULL DEFAULT 0,

    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;